USE SAA;
GO


CREATE TABLE FACULTY (
    FACULTY nvarchar(10) PRIMARY KEY,
    FACULTY_NAME nvarchar(50)
);

CREATE TABLE PULPIT (
    PULPIT nvarchar(10) PRIMARY KEY,
    PULPIT_NAME nvarchar(50),
    FACULTY nvarchar(10) FOREIGN KEY REFERENCES FACULTY(FACULTY)
);

CREATE TABLE SUBJECT (
    SUBJECT nvarchar(10) PRIMARY KEY,
    SUBJECT_NAME nvarchar(50),
    PULPIT nvarchar(10) FOREIGN KEY REFERENCES PULPIT(PULPIT)
);

CREATE TABLE AUDITORIUM_TYPE (
    AUDITORIUM_TYPE nvarchar(10) PRIMARY KEY,
    AUDITORIUM_TYPENAME nvarchar(50)
);

CREATE TABLE AUDITORIUM (
    AUDITORIUM nvarchar(10) PRIMARY KEY,
    AUDITORIUM_NAME nvarchar(50),
    AUDITORIUM_CAPACITY int,
    AUDITORIUM_TYPE nvarchar(10) FOREIGN KEY REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE)
);


CREATE TABLE TEACHER (
    TEACHER nvarchar(10) PRIMARY KEY,
    TEACHER_NAME nvarchar(50),
    PULPIT nvarchar(10) FOREIGN KEY REFERENCES PULPIT(PULPIT)

);

INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES
('MATH', 'Факультет математики'),
('CS', 'Факультет информатики');


INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY) VALUES 
('ISIT', 'Кафедра информатики', 'CS'), 
('HM', 'Кафедра высшей математики', 'MATH'),
('SE', 'Кафедра компьютерных наук', 'CS');


INSERT INTO TEACHER (TEACHER, TEACHER_NAME, PULPIT) VALUES
('IVANOV', 'Иванов Иван Иванович', 'ISIT'),
('PETROVA', 'Петрова Анна Сергеевна', 'HM');


INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES
('LK', 'Лекционный'),
('PR', 'Практический');


INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE) VALUES
('101-1', 'Аудитория 101', 30, 'LK'),
('102-1', 'Аудитория 102', 50, 'PR');


INSERT INTO SUBJECT (SUBJECT, SUBJECT_NAME, PULPIT) VALUES
('MA', 'Математический анализ', 'HM'),
('PROG', 'Программирование', 'ISIT');




SELECT * FROM FACULTY;
SELECT * FROM PULPIT;
SELECT * FROM TEACHER;
SELECT * FROM AUDITORIUM_TYPE;
SELECT * FROM AUDITORIUM;
SELECT * FROM SUBJECT;




USE SAA; 
GO
SELECT local_tcp_port
FROM sys.dm_exec_connections
WHERE session_id = @@SPID;